[package]
name = "xv6"
version = "0.1.0"
authors = ["TODO"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
x86 = "0.11.*"

[dev-dependencies]
proptest = "0.8"
